# Generated by Django 4.2.7 on 2025-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                help_text="image, document, audio, video",
                max_length=20,
                null=True,
            ),
        ),
    ]
