# Generated by Django 4.2.7 on 2025-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0003_userprofile_loginhistory_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="International phone number with country code",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="category",
            field=models.CharField(
                choices=[
                    ("faq", "FAQ"),
                    ("service", "Service"),
                    ("campaign", "Campaign Help"),
                    ("general", "General"),
                    ("escalation", "Escalation Trigger"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
