# Generated by Django 4.2.7 on 2025-11-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0005_add_tickets_learning_business_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatWidgetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Widget", max_length=100)),
                (
                    "button_color",
                    models.CharField(
                        default="#0006B1",
                        help_text="Hex color for the chat button",
                        max_length=7,
                    ),
                ),
                (
                    "button_position",
                    models.CharField(
                        choices=[
                            ("bottom-right", "Bottom Right"),
                            ("bottom-left", "Bottom Left"),
                            ("top-right", "Top Right"),
                            ("top-left", "Top Left"),
                        ],
                        default="bottom-right",
                        max_length=20,
                    ),
                ),
                (
                    "widget_width",
                    models.IntegerField(default=420, help_text="Width in pixels"),
                ),
                (
                    "widget_height",
                    models.IntegerField(default=600, help_text="Height in pixels"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
