# Generated by Django 4.2.7 on 2025-11-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0006_add_chat_widget_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwidgetconfig",
            name="bot_name",
            field=models.CharField(
                default="Ariho",
                help_text="Name of the AI bot assistant",
                max_length=100,
            ),
        ),
    ]
