# Generated by Django 4.2.7 on 2025-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0007_chatwidgetconfig_bot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwidgetconfig",
            name="bot_profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image for the bot",
                null=True,
                upload_to="bot_profiles/",
            ),
        ),
    ]
