# Generated by Django 4.2.7 on 2025-11-12 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat_app", "0009_agentchat_agentnote_agentmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="read_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="read_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer_notified",
            field=models.BooleanField(
                default=False, help_text="Whether customer has been notified via email"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="follow_up_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_to_follow_up",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="follow_up_date",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled follow-up date", null=True
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="follow_up_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for follow-up actions", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read", "created_at"], name="chat_app_me_is_read_a63798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["follow_up_date", "status"],
                name="chat_app_ti_follow__cd9b7c_idx",
            ),
        ),
    ]
