# Generated by Django 4.2.7 on 2025-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0010_message_is_read_message_read_at_message_read_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="has_left_message",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has already left a message while waiting for agent",
            ),
        ),
        migrations.CreateModel(
            name="WebsiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Extracted text content from the webpage"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata like headings, links, etc.",
                    ),
                ),
                ("last_scraped", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_scraped"],
                "indexes": [
                    models.Index(
                        fields=["url", "is_active"], name="chat_app_we_url_d9cf92_idx"
                    )
                ],
            },
        ),
    ]
