# Generated by Django 4.2.7 on 2025-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0011_chatsession_has_left_message_websitecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_intent",
            field=models.CharField(
                blank=True,
                help_text="Last detected intent for context",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="package_selected",
            field=models.CharField(
                blank=True,
                help_text="Selected pricing package",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="ticket_suggested",
            field=models.BooleanField(
                default=False, help_text="Whether ticket creation has been suggested"
            ),
        ),
    ]
