# Generated by Django 4.2.7 on 2025-11-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "chat_app",
            "0012_chatsession_last_intent_chatsession_package_selected_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="badge_count",
            field=models.IntegerField(
                default=0, help_text="Badge count for notification tabs"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sound_played",
            field=models.BooleanField(
                default=False, help_text="Whether notification sound has been played"
            ),
        ),
    ]
